databases:
  - name: marbix-db
    databaseName: marbix
    user: marbix_user
    region: oregon

services:
  - type: web
    name: marbix-api
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.marbix.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: marbix-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.0
    region: oregon
    plan: free
    # Add your other environment variables here
    # - key: SECRET_KEY
    #   value: your-secret-key
    # - key: GOOGLE_CLIENT_ID
    #   value: your-google-client-id