"""change make_request columns

Revision ID: 0fe7769b0e80
Revises: 675b3fba3688
Create Date: 2025-08-02 12:20:53.450988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe7769b0e80'
down_revision: Union[str, Sequence[str], None] = '675b3fba3688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('make_requests', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('make_requests', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('make_requests', sa.Column('callback_received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('make_requests', 'callback_received_at')
    op.drop_column('make_requests', 'max_retries')
    op.drop_column('make_requests', 'retry_count')
    # ### end Alembic commands ###
