"""change_sources_to_json_array_v2

Revision ID: 63bdcacae205
Revises: c1b9cb111d3c
Create Date: 2025-08-20 15:38:51.819531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bdcacae205'
down_revision: Union[str, Sequence[str], None] = 'c1b9cb111d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add a temporary JSON column
    op.add_column('make_requests', sa.Column('sources_json', sa.JSON(), nullable=True))
    
    # Step 2: Convert existing TEXT data to JSON arrays
    op.execute("""
        UPDATE make_requests 
        SET sources_json = CASE 
            WHEN sources IS NULL THEN '[]'::json
            WHEN sources = '' THEN '[]'::json
            WHEN sources LIKE '%\n%' THEN (
                SELECT COALESCE(json_agg(trim(url)), '[]'::json)
                FROM (
                    SELECT unnest(string_to_array(sources, '\n')) as url
                ) t
                WHERE trim(url) != ''
            )
            ELSE '[]'::json
        END
    """)
    
    # Step 3: Drop the old TEXT column
    op.drop_column('make_requests', 'sources')
    
    # Step 4: Rename the new JSON column to 'sources'
    op.alter_column('make_requests', 'sources_json', new_column_name='sources')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add a temporary TEXT column
    op.add_column('make_requests', sa.Column('sources_text', sa.TEXT(), nullable=True))
    
    # Step 2: Convert JSON arrays back to newline-separated text
    op.execute("""
        UPDATE make_requests 
        SET sources_text = CASE 
            WHEN sources IS NULL THEN ''
            WHEN json_array_length(sources) = 0 THEN ''
            ELSE array_to_string(ARRAY(SELECT json_array_elements_text(sources)), '\n')
        END
    """)
    
    # Step 3: Drop the old JSON column
    op.drop_column('make_requests', 'sources')
    
    # Step 4: Rename the new TEXT column to 'sources'
    op.alter_column('make_requests', 'sources_text', new_column_name='sources')
    
    # ### end Alembic commands ###
