"""added extra columns to make_request model

Revision ID: b0c54a1507cb
Revises: 0fcdc2a4d355
Create Date: 2025-08-02 11:04:44.660137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c54a1507cb'
down_revision: Union[str, Sequence[str], None] = '0fcdc2a4d355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('make_requests', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('make_requests', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('make_requests', sa.Column('callback_received_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('make_requests', 'callback_received_at')
    op.drop_column('make_requests', 'max_retries')
    op.drop_column('make_requests', 'retry_count')
    # ### end Alembic commands ###
