"""create_enhanced_strategies_table

Revision ID: c1b9cb111d3c
Revises: b2b4fdcc9b5c
Create Date: 2025-08-18 17:50:42.256951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b9cb111d3c'
down_revision: Union[str, Sequence[str], None] = 'b2b4fdcc9b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enhanced_strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_strategy_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', 'PARTIAL', name='enhancementstatus'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('Analys_rynka', sa.Text(), nullable=True),
    sa.Column('Drivers', sa.Text(), nullable=True),
    sa.Column('Competitors', sa.Text(), nullable=True),
    sa.Column('Customer_Journey', sa.Text(), nullable=True),
    sa.Column('Product', sa.Text(), nullable=True),
    sa.Column('Communication', sa.Text(), nullable=True),
    sa.Column('TEAM', sa.Text(), nullable=True),
    sa.Column('Metrics', sa.Text(), nullable=True),
    sa.Column('Next_Steps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['original_strategy_id'], ['make_requests.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhanced_strategies_id'), 'enhanced_strategies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enhanced_strategies_id'), table_name='enhanced_strategies')
    op.drop_table('enhanced_strategies')
    # ### end Alembic commands ###
